# Generated by Django 4.1.2 on 2022-10-24 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.TextField()),
                ('organiser', models.TextField()),
                ('numberofseats', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(400)])),
                ('dateofevent', models.CharField(max_length=12)),
            ],
        ),
    ]
