# Generated by Django 4.1.2 on 2022-10-27 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisers', '0002_alter_eventitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventitem',
            name='organiser',
        ),
        migrations.AddField(
            model_name='eventitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventitem',
            name='dateofevent',
            field=models.DateTimeField(),
        ),
    ]
