# Generated by Django 4.1.2 on 2022-10-27 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisers', '0003_remove_eventitem_organiser_eventitem_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
