# Generated by Django 4.1.2 on 2022-10-28 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisers', '0004_alter_eventitem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=b'I01\n', serialize=False, to='organisers.eventitem')),
                ('seatbooked', models.IntegerField(default=1)),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
