# Generated by Django 4.1.2 on 2022-10-30 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisers', '0006_alter_booking_book_alter_booking_seatbooked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='book',
        ),
        migrations.AddField(
            model_name='booking',
            name='booker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=b'I01\n', serialize=False, to='organisers.eventitem'),
        ),
    ]
